### ISSUE TITLE
KAT Checklist

### ISSUE THREAD

**Issue by pxgamer** [pxgamer/kickass-torrents-cp#5]
## Account
- [x] Add profile page
- [ ] Add tabs:
  - [ ] Profile (default)
  - [ ] Albums
  - [ ] Friends
  - [ ] Requests
  - [ ] Threads
  - [ ] Blog
  - [ ] Comments
  - [ ] Uploads
  - [ ] Moderation
  - [ ] Messages
- [x] Add custom title editing
- [x] Add title clearing page
- [x] Add `assign bonus` page
- [ ] Add settings page:
  - [ ] Profile
  - [ ] General
  - [ ] Signature
  - [ ] Browsing
  - [ ] Privacy
  - [ ] FrontPage Widgets
- [ ] Add ability to hide the sidebar

## Auth
- [x] Add login page
- [x] Add register page
- [x] Add logout function
- [x] Add validation
- [x] Add sudo
- [x] Add user switch
- [x] Add user switch-back
- [x] Add hash regeneration

## Blog
- [ ] Add index
- [ ] Add user blog browsing (`/blog/{user}`)
- [x] Add page for creating blogs
- [ ] Add function to post a blog (`public function post() { ... }`)
- [x] Add page for editing blogs
- [ ] Add ability to delete blogs
- [ ] Add ability to undelete blogs

## Browse
- [ ] Add page for browsing torrents
- [ ] Add page for searching torrents
- [ ] Add page for each category:
  - [ ] Latest
  - [ ] Movies
  - [ ] TV
  - [ ] Music
  - [ ] Games
  - [ ] Books
  - [ ] Apps
  - [ ] Anime
  - [ ] Other
  - [ ] XXX

## Community
- [x] Add index page
- [x] Add forum category pages
- [x] Add page for showing threads (`/community/show/{id}`)
- [x] Add page for creating threads
- [x] Add page for editing threads
- [ ] Add functions for forums:
  - [x] Create a forum
  - [x] Edit a forum
  - [x] Delete a forum
  - [x] Un-Delete a forum
  - [x] Reorder a forum
- [ ] Add functions for threads:
  - [x] Delete
  - [x] Un-Delete
  - [x] Sticky
  - [x] Un-Sticky
  - [x] Lock
  - [x] Unlock
  - [x] Move
  - [ ] Assign Ownership
  - [ ] Merge
- [ ] Add functions for posts:
  - [x] Create
  - [x] Edit
  - [x] Like
  - [x] Dislike
  - [x] Remove Rating
  - [x] Delete
  - [x] Un-Delete
- [ ] Add functions for polls
  - [x] Create
  - [x] Vote
  - [x] Get Voters
  - [ ] Edit
  - [ ] Close
  - [ ] Open
  - [ ] Delete

## Content
- [ ] Index page
- [ ] Create content
- [ ] Edit content
- [ ] Add rules page

## Event Log
- [ ] Index page
- [ ] Thread events
- [ ] User events

## Images
- [ ] Upload page
- [ ] Index page

## Main
- [ ] Index page (for root)
- [ ] devkit

## Messenger
- [ ] Index page
- [ ] Functions for messages:
  - [x] Create
  - [x] Check unread
  - [ ] Forward PMs
  - [x] Delete PMs

## Moderation
- [x] Index page redirect
- [ ] Functions for moderation:
  - [ ] Tier 1/2/3 promotions
  - [ ] Summaries
  - [ ] Requests
  - [ ] Ideas
  - [ ] Reports:
    - [ ] Torrents
    - [ ] Users
    - [ ] Summaries
  - [ ] IP Management
  - [ ] Comments history

## Not Found
- [ ] 404 index page

## Torrents
- [ ] Functions for torrents:
  - [ ] Create
  - [ ] Edit
  - [ ] Delete
  - [ ] Un-Delete
  - [ ] Verify
  - [ ] Un-Verify

**Comment by pxgamer** [comment]
Stopping development to work on TorrentTrader instead.
